In [2]:
import torch
import numpy as np
# import pytorch_learn.Tensor_create --- IGNORE ---


1.基本张量创建
1.1按内容创建张亮

In [3]:
tensor1 = torch.tensor([10.0])
print(tensor1)

tensor([10.])


In [4]:
tensor2 = torch.tensor([1.0,2.0,3.0])
print(tensor2)

tensor([1., 2., 3.])


In [5]:
#传入np.ndarray
ndarray = np.array([[1,2],[3,4]])
tensor3 = torch.tensor(ndarray)
print(tensor3)


tensor([[1, 2],
        [3, 4]])


In [6]:
print(tensor3.size())

torch.Size([2, 2])


1.2创建指定形状的张量

In [8]:
tensor4 = torch.Tensor(3,2,4)
print(tensor4.size())
print(tensor4)
print(tensor4.dtype)

torch.Size([3, 2, 4])
tensor([[[1.3314e+05, 1.8511e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.float32


In [9]:
ndarray = np.array([[1,2],[3,4]])
tensor4 = torch.Tensor(ndarray)
print(tensor4.size())
print(tensor4)
print(tensor4.dtype)

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.float32


1.3指定类型张量

In [10]:
tensor1 = torch.IntTensor([1,2,3])
print(tensor1)
tensor2 = torch.FloatTensor(2,3)
print(tensor2)
print(tensor2.dtype)
tensor3 = torch.tensor([1,2,3],dtype=torch.float64)
print(tensor3)
print(tensor3.dtype)

tensor([1, 2, 3], dtype=torch.int32)
tensor([[1.3315e+05, 1.8511e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.float32
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


1.4指定区间创建张量

In [11]:
tensor1 = torch.arange(0,10,2)
print(tensor1)

tensor([0, 2, 4, 6, 8])


In [14]:
tensor1 = torch.linspace(10,100,9)
print(tensor1)

tensor([ 10.0000,  21.2500,  32.5000,  43.7500,  55.0000,  66.2500,  77.5000,
         88.7500, 100.0000])


In [15]:
tensor1 = torch.logspace(10,100,9,2)
print(tensor1)

tensor([1.0240e+03, 2.4939e+06, 6.0740e+09, 1.4793e+13, 3.6029e+16, 8.7748e+19,
        2.1371e+23, 5.2049e+26, 1.2677e+30])


1.5特定值创建张量

In [17]:
tensor1 = torch.zeros(2,3,4)
print(tensor1)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [18]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [19]:
tensor3 = torch.full((2,3,4),9)
print(tensor3)

tensor([[[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]],

        [[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]]])


In [20]:
tensor1 = torch.eye(3,5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
